// #![warn(unused_crate_dependencies)]

use std::fs;
use std::path::PathBuf;

use anyhow::{Result, anyhow};
use clap::{Parser, Subcommand};
use consensus_config::{Authority, Parameters};
use consensus_core::CommitConsumerArgs;
use evm_consensus::evm::{
    RawTransactionClient, extract_peer_addresses, generate_committees, generate_genesis_config,
    generate_validators, load_committees,
};
use execute::validator::ValidatorNode;
use mysten_metrics::{RegistryService, monitored_mpsc::unbounded_channel};
use prometheus::Registry;
use serde::{Deserialize, Serialize};
use serde_yaml;
use tokio::signal;
use tracing::{Level, error, info};
use tracing_subscriber;

#[derive(Default, Serialize, Deserialize)]
struct NodeConfig {
    chain: String, // Can be predefined name (mainnet, sepolia, holesky, hoodi, dev) or path to custom genesis
    committee_path: String,
    parameters_path: String, // Path to consensus parameters YAML file
    execution_http_url: String,
    execution_ws_url: String,
    jwt_secret: String,
    genesis_time: u64,
    genesis_block_hash: String,
    fee_recipient: String,
    poll_interval: u64,
    max_retries: u32,
    timeout: u64,
    working_directory: String,
    peer_addresses: Vec<String>,
    node_index: u32,
    log_level: String,
}

#[derive(Parser, Debug)]
#[command(name = "fastevm-consensus")]
#[command(about = "FastEVM Consensus Client - Mysticeti Engine API Bridge")]
struct Args {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Generate validator configurations file
    GenerateValidators {
        /// Output file path for the validator configurations
        #[arg(short, long, default_value = "validators.yml")]
        output: PathBuf,

        /// Number of authorities in the committee
        #[arg(short, long, default_value = "4")]
        authorities: usize,

        /// Epoch number
        #[arg(short, long, default_value = "0")]
        epoch: u64,

        /// Stake per authority
        #[arg(short, long, default_value = "1")]
        stake: u64,

        /// Docker IP addresses for the authorities (comma-separated)
        #[arg(
            long,
            default_value = "172.20.0.10,172.20.0.11,172.20.0.12,172.20.0.13"
        )]
        ip_addresses: String,

        /// Network ports for the authorities (comma-separated)
        #[arg(long, default_value = "26657,26657,26657,26657")]
        network_ports: String,

        /// Hostname prefix for the authorities
        #[arg(long, default_value = "fastevm-consensus")]
        hostname_prefix: String,
    },

    /// Generate a genesis configuration JSON file from validators.yml
    GenerateGenesisConfig {
        /// Path to validator config file (generated by GenerateValidators)
        #[arg(long, default_value = "validators.yml")]
        config_path: PathBuf,

        /// Output file path for the genesis configuration
        #[arg(short, long, default_value = "genesis.json")]
        genesis_path: PathBuf,
    },

    /// Generate a committee configuration file from validators.yml
    GenerateCommittee {
        /// Path to validator config file (generated by GenerateValidators)
        #[arg(long, default_value = "validators.yml")]
        config_path: PathBuf,

        /// Output file path for the committee configuration
        #[arg(short, long, default_value = "committees.yml")]
        committee_path: PathBuf,

        /// Epoch number (overrides epoch from validator config if provided)
        #[arg(short, long)]
        epoch: Option<u64>,
    },

    /// Start the consensus node
    Start {
        /// Path to committee configuration file
        #[arg(short, long, default_value = "config.yml")]
        config: PathBuf,
    },
}

/// Starts the consensus client with the given configuration
async fn start_consensus_client(config_path: &PathBuf) -> Result<()> {
    // Load the full configuration
    let config_content = fs::read_to_string(config_path)?;
    let mut node_config: NodeConfig = serde_yaml::from_str(&config_content)?;
    let content = std::fs::read_to_string(&node_config.parameters_path)?;
    let parameters: Parameters = serde_yaml::from_str(&content)?;
    // Load committee configuration from file
    let committee_path = PathBuf::from(&node_config.committee_path);
    let (committee, keypairs) = load_committees(&committee_path)?;
    let authorities: Vec<Authority> = committee
        .authorities()
        .map(|(_, authority)| authority.clone())
        .collect();
    node_config.peer_addresses = extract_peer_addresses(&committee);
    // Initialize tracing
    let log_level = match node_config.log_level.as_str() {
        "trace" => Level::TRACE,
        "debug" => Level::DEBUG,
        "info" => Level::INFO,
        "warn" => Level::WARN,
        "error" => Level::ERROR,
        _ => Level::INFO,
    };

    tracing_subscriber::fmt()
        .with_max_level(log_level)
        .with_target(false)
        .init();

    info!(
        "Starting FastEVM Consensus Client (Node {}, Execution HTTP URL: {}, Execution WS URL: {}, Working Directory: {}, Fee Recipient: {})",
        node_config.node_index,
        node_config.execution_http_url,
        node_config.execution_ws_url,
        node_config.working_directory,
        node_config.fee_recipient,
    );

    // Create validator node
    let mut validator = ValidatorNode::new(
        node_config.node_index,
        PathBuf::from(&node_config.working_directory),
    );

    // Create metrics registry
    let registry_service = RegistryService::new(Registry::new());
    // Create channels for exchange payload between engine client and consensus process
    let (tx_transactions, rx_transactions) = unbounded_channel("raw_transactions");
    // Create channels for exchange block between engine client and consensus process
    // Create commit consumer
    let (commit_consumer, commit_receiver, _block_receiver) = CommitConsumerArgs::new(0, 0);
    // Start the validator node
    validator
        .start(
            committee,
            parameters,
            keypairs,
            registry_service,
            commit_consumer,
            rx_transactions,
        )
        .await
        .map_err(|e| anyhow!("Failed to start validator node: {}", e))?;

    // Create and start the Engine API client
    let mut client = RawTransactionClient::new(
        authorities,
        node_config.jwt_secret,
        node_config.execution_http_url,
        node_config.execution_ws_url,
        tx_transactions,
    );

    info!("Consensus client starting with transaction subscription...");

    // Start the main client loop
    let client_handle = tokio::spawn(async move {
        match client.start(commit_receiver).await {
            Ok(()) => info!("Engine API client stopped normally"),
            Err(e) => error!("Engine API client failed: {}", e),
        }
    });

    // Keep the main function alive by waiting for shutdown signal or client failure
    // This prevents the container from exiting
    info!(
        "Consensus client started successfully. Waiting for shutdown signal or client failure..."
    );

    // Handle signals properly
    let mut sigterm = signal::unix::signal(signal::unix::SignalKind::terminate())
        .map_err(|e| anyhow!("Failed to create SIGTERM handler: {}", e))?;

    tokio::select! {
        _ = signal::ctrl_c() => {
            info!("Received shutdown signal, shutting down...");
        }
        _ = sigterm.recv() => {
            info!("Received SIGTERM, shutting down...");
        }
        client_result = client_handle => {
            match client_result {
                Ok(_) => info!("Engine API client completed"),
                Err(e) => error!("Engine API client task failed: {}", e),
            }
        }
    }

    Ok(())
}

fn main() -> Result<()> {
    let args = Args::parse();

    match args.command {
        Commands::GenerateValidators {
            output,
            authorities,
            epoch,
            stake,
            ip_addresses,
            network_ports,
            hostname_prefix,
        } => {
            // Parse comma-separated strings into vectors
            let ips_vec: Vec<String> = ip_addresses
                .split(',')
                .map(|s| s.trim().to_string())
                .collect();
            let network_ports_vec: Vec<u16> = network_ports
                .split(',')
                .map(|s| {
                    let trimmed = s.trim();
                    trimmed.parse::<u16>().unwrap_or_else(|_| {
                        eprintln!("Warning: Invalid port '{}', using default 26657", trimmed);
                        26657
                    })
                })
                .collect();

            generate_validators(
                &output,
                authorities,
                epoch,
                stake,
                &ips_vec,
                &network_ports_vec,
                hostname_prefix.as_str(),
            )
            .map_err(|e| anyhow!("Failed to generate validator config: {}", e))?;
        }
        Commands::GenerateCommittee {
            config_path,
            committee_path,
            epoch,
        } => {
            generate_committees(&config_path, &committee_path, epoch)
                .map_err(|e| anyhow!("Failed to generate committee config: {}", e))?;
        }
        Commands::GenerateGenesisConfig {
            config_path,
            genesis_path,
        } => {
            generate_genesis_config(&config_path, &genesis_path)
                .map_err(|e| anyhow!("Failed to generate genesis config: {}", e))?;
        }
        Commands::Start { config } => {
            // Only create tokio runtime for async Start command
            tokio::runtime::Runtime::new()
                .map_err(|e| anyhow!("Failed to create tokio runtime: {}", e))?
                .block_on(start_consensus_client(&config))?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use tempfile::tempdir;

    // Helper function to create test config file
    fn create_test_config_file() -> (PathBuf, PathBuf) {
        let temp_dir = tempdir().unwrap();
        let config_path = temp_dir.path().join("config.yml");
        let committee_path = temp_dir.path().join("committee.yml");

        let config_content = r#"
committee_path: committee.yml
execution_url: http://127.0.0.1:8551
jwt_secret: 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
fee_recipient: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
poll_interval: 1000
max_retries: 3
timeout: 5000
working_directory: /tmp/test
peer_addresses: []
node_index: 0
log_level: info
"#;

        let committee_content = r#"
epoch: 1
authorities:
  - index: 0
    stake: 1000
    hostname: test-node0
    address: /ip4/172.20.0.10/udp/26657
    authority_key: key1
    protocol_key: key2
    network_key: key3
  - index: 1
    stake: 1000
    hostname: test-node1
    address: /ip4/172.20.0.11/udp/26658
    authority_key: key4
    protocol_key: key5
    network_key: key6
docker_network:
  base_ip: 172.20.0
  start_ip: 10
  end_ip: 11
  port: 26657
quorum_threshold: 2
validity_threshold: 1
"#;

        fs::write(&config_path, config_content).unwrap();
        fs::write(&committee_path, committee_content).unwrap();

        (config_path, committee_path)
    }

    #[test]
    fn test_args_parsing() {
        // Test that Args can be created (this tests the derive macro)
        let args = Args {
            command: Commands::GenerateValidators {
                output: PathBuf::from("validators.yml"),
                authorities: 4,
                epoch: 1,
                stake: 1000,
                ip_addresses: "172.20.0.10,172.20.0.11".to_string(),
                network_ports: "26657,26658".to_string(),
                hostname_prefix: "fastevm-consensus".to_string(),
            },
        };

        assert!(matches!(args.command, Commands::GenerateValidators { .. }));

        let args2 = Args {
            command: Commands::GenerateCommittee {
                config_path: PathBuf::from("validators.yml"),
                committee_path: PathBuf::from("test.yml"),
                epoch: Some(1),
            },
        };

        assert!(matches!(args2.command, Commands::GenerateCommittee { .. }));

        let args3 = Args {
            command: Commands::Start {
                config: PathBuf::from("config.yml"),
            },
        };

        assert!(matches!(args3.command, Commands::Start { .. }));
    }

    #[test]
    fn test_commands_variants() {
        // Test GenerateValidators command
        let generate_validators_cmd = Commands::GenerateValidators {
            output: PathBuf::from("validators.yml"),
            authorities: 5,
            epoch: 2,
            stake: 2000,
            ip_addresses: "192.168.1.1,192.168.1.2".to_string(),
            network_ports: "8080,8081".to_string(),
            hostname_prefix: "fastevm-consensus".to_string(),
        };

        match generate_validators_cmd {
            Commands::GenerateValidators {
                output,
                authorities,
                epoch,
                stake,
                ip_addresses,
                network_ports,
                hostname_prefix,
            } => {
                assert_eq!(output, PathBuf::from("validators.yml"));
                assert_eq!(authorities, 5);
                assert_eq!(epoch, 2);
                assert_eq!(stake, 2000);
                assert_eq!(ip_addresses, "192.168.1.1,192.168.1.2");
                assert_eq!(network_ports, "8080,8081");
                assert_eq!(hostname_prefix, "fastevm-consensus");
            }
            _ => panic!("Expected GenerateValidators command"),
        }

        // Test GenerateCommittee command
        let generate_committee_cmd = Commands::GenerateCommittee {
            config_path: PathBuf::from("validators.yml"),
            committee_path: PathBuf::from("output.yml"),
            epoch: Some(2),
        };

        match generate_committee_cmd {
            Commands::GenerateCommittee {
                config_path,
                committee_path,
                epoch,
            } => {
                assert_eq!(config_path, PathBuf::from("validators.yml"));
                assert_eq!(committee_path, PathBuf::from("output.yml"));
                assert_eq!(epoch, Some(2));
            }
            _ => panic!("Expected GenerateCommittee command"),
        }

        // Test Start command
        let start_cmd = Commands::Start {
            config: PathBuf::from("start.yml"),
        };

        match start_cmd {
            Commands::Start { config } => {
                assert_eq!(config, PathBuf::from("start.yml"));
            }
            _ => panic!("Expected Start command"),
        }
    }

    #[test]
    fn test_log_level_parsing() {
        let test_cases = vec![
            ("trace", Level::TRACE),
            ("debug", Level::DEBUG),
            ("info", Level::INFO),
            ("warn", Level::WARN),
            ("error", Level::ERROR),
            ("invalid", Level::INFO), // Default fallback
            ("", Level::INFO),        // Empty string fallback
        ];

        for (input, expected) in test_cases {
            let result = match input {
                "trace" => Level::TRACE,
                "debug" => Level::DEBUG,
                "info" => Level::INFO,
                "warn" => Level::WARN,
                "error" => Level::ERROR,
                _ => Level::INFO,
            };

            assert_eq!(result, expected);
        }
    }

    #[tokio::test]
    async fn test_start_consensus_client_basic() {
        let (config_path, _committee_path) = create_test_config_file();

        // This test verifies that the function can be called without panicking
        // The actual result may vary depending on the consensus client setup
        let result = start_consensus_client(&config_path).await;

        // Test passes if we can call the function without panicking
        // The actual result may be an error due to missing dependencies
        assert!(true);
    }

    #[tokio::test]
    async fn test_start_consensus_client_with_invalid_config() {
        let temp_dir = tempdir().unwrap();
        let invalid_config_path = temp_dir.path().join("invalid.yml");

        // Create an invalid config file
        let invalid_content = r#"
invalid_field: value
missing_required_fields: true
"#;
        fs::write(&invalid_config_path, invalid_content).unwrap();

        // This should handle invalid config gracefully
        let result = start_consensus_client(&invalid_config_path).await;

        // Test passes if we can handle invalid input without panicking
        assert!(true);
    }

    #[tokio::test]
    async fn test_start_consensus_client_with_missing_committee() {
        let temp_dir = tempdir().unwrap();
        let config_path = temp_dir.path().join("config.yml");

        let config_content = r#"
committee_path: missing_committee.yml
execution_url: http://127.0.0.1:8551
jwt_secret: 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
fee_recipient: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
poll_interval: 1000
max_retries: 3
timeout: 5000
working_directory: /tmp/test
peer_addresses: []
node_index: 0
log_level: info
"#;

        fs::write(&config_path, config_content).unwrap();

        // This should handle missing committee file gracefully
        let result = start_consensus_client(&config_path).await;

        // Test passes if we can handle missing files without panicking
        assert!(true);
    }

    #[test]
    fn test_parse_comma_separated_strings() {
        let test_cases = vec![
            ("a,b,c", vec!["a", "b", "c"]),
            ("1,2,3", vec!["1", "2", "3"]),
            ("single", vec!["single"]),
            ("", vec![""]),
            ("a, b , c", vec!["a", "b", "c"]), // With spaces - should be trimmed
        ];

        for (input, expected) in test_cases {
            let result: Vec<String> = input.split(',').map(|s| s.trim().to_string()).collect();
            assert_eq!(result, expected);
        }
    }

    #[test]
    fn test_parse_comma_separated_ports() {
        let test_cases = vec![
            ("26657,26658,26659", vec![26657, 26658, 26659]),
            ("8080,8081", vec![8080, 8081]),
            ("80", vec![80]),
            ("invalid,8080", vec![26657, 8080]), // First invalid, second valid
            ("", vec![26657]),                   // Empty string defaults to 26657
        ];

        for (input, expected) in test_cases {
            let result: Vec<u16> = input
                .split(',')
                .map(|s| s.trim().parse::<u16>().unwrap_or(26657))
                .collect();
            assert_eq!(result, expected);
        }
    }

    #[test]
    fn test_parse_comma_separated_ips() {
        let test_cases = vec![
            (
                "172.20.0.10,172.20.0.11",
                vec!["172.20.0.10", "172.20.0.11"],
            ),
            ("192.168.1.1", vec!["192.168.1.1"]),
            (
                "10.0.0.1,10.0.0.2,10.0.0.3",
                vec!["10.0.0.1", "10.0.0.2", "10.0.0.3"],
            ),
        ];

        for (input, expected) in test_cases {
            let result: Vec<String> = input.split(',').map(|s| s.trim().to_string()).collect();
            assert_eq!(result, expected);
        }
    }

    #[test]
    fn test_registry_service_creation() {
        let registry = Registry::new();
        let registry_service = RegistryService::new(registry);

        // Test that we can create the registry service
        assert!(true);
    }

    #[test]
    fn test_validator_node_creation() {
        let working_directory = PathBuf::from("/tmp/test");
        let validator = ValidatorNode::new(0, working_directory);

        // Test that we can create the validator node
        assert!(true);
    }

    #[test]
    fn test_path_operations() {
        let base_path = PathBuf::from("/tmp");
        let sub_path = base_path.join("test");
        let final_path = sub_path.join("config.yml");

        assert_eq!(final_path, PathBuf::from("/tmp/test/config.yml"));
        assert!(final_path.to_string_lossy().contains("config.yml"));
    }

    #[test]
    fn test_string_operations() {
        let test_string = "test_value";
        let trimmed = test_string.trim();
        let parsed: u16 = "8080".parse().unwrap();

        assert_eq!(trimmed, "test_value");
        assert_eq!(parsed, 8080);
    }

    #[test]
    fn test_error_handling() {
        // Test that we can create anyhow errors
        let error = anyhow::anyhow!("Test error message");
        let error_string = error.to_string();

        assert!(error_string.contains("Test error message"));
    }

    #[test]
    fn test_file_operations() {
        let temp_dir = tempdir().unwrap();
        let test_file = temp_dir.path().join("test.txt");

        // Test file writing
        let content = "test content";
        let write_result = fs::write(&test_file, content);
        assert!(write_result.is_ok());

        // Test file reading
        let read_result = fs::read_to_string(&test_file);
        assert!(read_result.is_ok());
        assert_eq!(read_result.unwrap(), content);
    }

    #[test]
    fn test_yaml_parsing() {
        let yaml_content = r#"
key1: value1
key2: value2
nested:
  key3: value3
"#;

        let parsed: serde_yaml::Value = serde_yaml::from_str(yaml_content).unwrap();

        assert_eq!(parsed["key1"], "value1");
        assert_eq!(parsed["key2"], "value2");
        assert_eq!(parsed["nested"]["key3"], "value3");
    }

    #[test]
    fn test_mpsc_channel_creation() {
        use tokio::sync::mpsc;
        let (tx, mut rx) = mpsc::unbounded_channel::<String>();

        // Test sending
        let send_result = tx.send("test".to_string());
        assert!(send_result.is_ok());

        // Test receiving
        let recv_result = rx.try_recv();
        assert!(recv_result.is_ok());
        assert_eq!(recv_result.unwrap(), "test");
    }

    #[test]
    fn test_tokio_spawn() {
        // Create a Tokio runtime for the test
        let rt = tokio::runtime::Runtime::new().unwrap();
        rt.block_on(async {
            let handle = tokio::spawn(async { "test result".to_string() });
            let result = handle.await.unwrap();
            assert_eq!(result, "test result");
        });
    }

    #[test]
    fn test_generate_committee_command_execution() {
        use tempfile::tempdir;

        // Test with exact parameters:
        // First generate validators, then generate committee from validators
        let temp_dir = tempdir().unwrap();
        let config_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");

        // Simulate the command-line argument parsing
        let ip_addresses = "127.0.0.1,127.0.0.1,127.0.0.1,127.0.0.1";
        let network_ports = "26657,26658,26659,26660";

        // Parse comma-separated strings into vectors (same as in main)
        let ips_vec: Vec<String> = ip_addresses
            .split(',')
            .map(|s| s.trim().to_string())
            .collect();
        let network_ports_vec: Vec<u16> = network_ports
            .split(',')
            .map(|s| s.trim().parse::<u16>().unwrap_or(26657))
            .collect();

        // First generate validators
        let result = generate_validators(
            &config_path,
            4,    // authorities
            0,    // epoch
            1000, // stake
            &ips_vec,
            &network_ports_vec,
            "fastevm-consensus", // hostname_prefix (default)
        );
        assert!(result.is_ok(), "generate_validators should succeed");
        assert!(config_path.exists(), "Validators file should be created");

        // Then generate committee from validators
        let result = generate_committees(&config_path, &committee_path, Some(0));
        assert!(
            result.is_ok(),
            "generate_committees should succeed: {:?}",
            result
        );
        assert!(committee_path.exists(), "Committee file should be created");

        // Verify file content
        let file_content = fs::read_to_string(&committee_path).unwrap();
        let config: serde_yaml::Value = serde_yaml::from_str(&file_content).unwrap();

        // Verify basic structure
        assert_eq!(config["epoch"], 0);
        assert_eq!(config["authorities"].as_sequence().unwrap().len(), 4);
        assert_eq!(config["quorum_threshold"], 2667); // (4 * 2) / 3 + 1 = 3
        assert_eq!(config["validity_threshold"], 1334); // 4 / 2 + 1 = 3

        // Verify each authority has correct structure
        let authorities = config["authorities"].as_sequence().unwrap();
        for (i, authority) in authorities.iter().enumerate() {
            assert_eq!(authority["index"], i);
            assert_eq!(authority["stake"], 1000);
            assert_eq!(
                authority["hostname"].as_str().unwrap(),
                format!("fastevm-consensus{}", i)
            );
            assert_eq!(
                authority["address"].as_str().unwrap(),
                format!("/ip4/127.0.0.1/udp/{}", network_ports_vec[i])
            );
            // Verify keys are present
            assert!(authority["authority_key"].as_str().is_some());
            assert!(authority["protocol_key"].as_str().is_some());
            assert!(authority["network_key"].as_str().is_some());
        }

        // Verify docker network configuration
        assert_eq!(
            config["docker_network"]["base_ip"].as_str().unwrap(),
            "172.20.0"
        );
        assert_eq!(config["docker_network"]["start_ip"], 10);
        assert_eq!(config["docker_network"]["end_ip"], 13); // 10 + 4 - 1
        assert_eq!(config["docker_network"]["port"], 26657);
    }

    #[test]
    fn test_generate_committee_command_with_parsing_edge_cases() {
        use tempfile::tempdir;

        let temp_dir = tempdir().unwrap();
        let config_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");

        // Test with spaces in the comma-separated strings
        let ip_addresses = "127.0.0.1, 127.0.0.1, 127.0.0.1, 127.0.0.1";
        let network_ports = "26657, 26658, 26659, 26660";

        let ips_vec: Vec<String> = ip_addresses
            .split(',')
            .map(|s| s.trim().to_string())
            .collect();
        let network_ports_vec: Vec<u16> = network_ports
            .split(',')
            .map(|s| s.trim().parse::<u16>().unwrap_or(26657))
            .collect();

        assert_eq!(ips_vec.len(), 4);
        assert_eq!(network_ports_vec.len(), 4);
        assert_eq!(network_ports_vec, vec![26657, 26658, 26659, 26660]);

        // First generate validators
        let result = generate_validators(
            &config_path,
            4,
            0,
            1000,
            &ips_vec,
            &network_ports_vec,
            "test",
        );
        assert!(result.is_ok());
        assert!(config_path.exists());

        // Then generate committee from validators
        let result = generate_committees(&config_path, &committee_path, Some(0));
        assert!(result.is_ok());
        assert!(committee_path.exists());
    }

    #[test]
    fn test_create_evm_consensus_full_workflow() {
        use tempfile::tempdir;

        // Test the complete workflow: generate validators -> generate committee -> generate genesis
        let temp_dir = tempdir().unwrap();
        let validators_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");
        let genesis_path = temp_dir.path().join("genesis.json");

        let authorities = 4;
        let epoch = 0;
        let stake = 1000;
        let ip_addresses = vec![
            "127.0.0.1".to_string(),
            "127.0.0.1".to_string(),
            "127.0.0.1".to_string(),
            "127.0.0.1".to_string(),
        ];
        let network_ports = vec![26657, 26658, 26659, 26660];
        let hostname_prefix = "fastevm-consensus";

        // Step 1: Generate validators
        let result = generate_validators(
            &validators_path,
            authorities,
            epoch,
            stake,
            &ip_addresses,
            &network_ports,
            hostname_prefix,
        );
        assert!(result.is_ok(), "generate_validators should succeed");
        assert!(
            validators_path.exists(),
            "Validators file should be created"
        );

        // Step 2: Generate committee from validators
        let result = generate_committees(&validators_path, &committee_path, Some(epoch));
        assert!(result.is_ok(), "generate_committees should succeed");
        assert!(committee_path.exists(), "Committee file should be created");

        // Step 3: Generate genesis config from validators
        let result = generate_genesis_config(&validators_path, &genesis_path);
        assert!(result.is_ok(), "generate_genesis_config should succeed");
        assert!(genesis_path.exists(), "Genesis file should be created");

        // Verify all files can be loaded
        let (committee, keypairs) = load_committees(&committee_path).unwrap();
        assert_eq!(committee.size(), authorities);
        assert_eq!(keypairs.len(), authorities);

        // Verify genesis config can be loaded
        let genesis_content = fs::read_to_string(&genesis_path).unwrap();
        let genesis_config: serde_json::Value = serde_json::from_str(&genesis_content).unwrap();
        assert_eq!(
            genesis_config["validatorAddresses"]
                .as_array()
                .unwrap()
                .len(),
            authorities
        );
        assert_eq!(
            genesis_config["consensusPublicKeys"]
                .as_array()
                .unwrap()
                .len(),
            authorities
        );
    }

    #[test]
    fn test_create_evm_consensus_with_different_configurations() {
        use tempfile::tempdir;

        // Test with different numbers of authorities
        let test_cases = vec![
            (1, 1, 1000),  // Single authority
            (3, 0, 5000),  // Three authorities, different epoch and stake
            (7, 10, 2000), // Seven authorities
        ];

        for (authorities, epoch, stake) in test_cases {
            let temp_dir = tempdir().unwrap();
            let validators_path = temp_dir.path().join("validators.yml");
            let committee_path = temp_dir.path().join("committees.yml");
            let genesis_path = temp_dir.path().join("genesis.json");

            let ip_addresses: Vec<String> = (0..authorities)
                .map(|i| format!("127.0.0.{}", i + 1))
                .collect();
            let network_ports: Vec<u16> = (0..authorities).map(|i| 26657 + i as u16).collect();

            // Generate validators
            let result = generate_validators(
                &validators_path,
                authorities,
                epoch,
                stake,
                &ip_addresses,
                &network_ports,
                "test-node",
            );
            assert!(
                result.is_ok(),
                "generate_validators should succeed for {} authorities",
                authorities
            );

            // Generate committee
            let result = generate_committees(&validators_path, &committee_path, Some(epoch));
            assert!(
                result.is_ok(),
                "generate_committees should succeed for {} authorities",
                authorities
            );

            // Generate genesis
            let result = generate_genesis_config(&validators_path, &genesis_path);
            assert!(
                result.is_ok(),
                "generate_genesis_config should succeed for {} authorities",
                authorities
            );

            // Verify committee thresholds
            let (committee, _) = load_committees(&committee_path).unwrap();
            assert_eq!(committee.size(), authorities);
            assert_eq!(committee.epoch(), epoch);
        }
    }

    #[test]
    fn test_create_evm_consensus_error_handling() {
        use tempfile::tempdir;

        let temp_dir = tempdir().unwrap();
        let validators_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");
        let genesis_path = temp_dir.path().join("genesis.json");

        // Test: Generate validators with insufficient IPs
        let result = generate_validators(
            &validators_path,
            5, // 5 authorities
            0,
            1000,
            &vec!["127.0.0.1".to_string(); 3], // Only 3 IPs
            &vec![26657, 26658, 26659, 26660, 26661],
            "test",
        );
        assert!(result.is_err(), "Should fail with insufficient IPs");

        // Test: Generate validators with insufficient ports
        let result = generate_validators(
            &validators_path,
            5, // 5 authorities
            0,
            1000,
            &vec!["127.0.0.1".to_string(); 5],
            &vec![26657, 26658, 26659], // Only 3 ports
            "test",
        );
        assert!(result.is_err(), "Should fail with insufficient ports");

        // Test: Generate committee from non-existent validators file
        let result = generate_committees(&validators_path, &committee_path, None);
        assert!(
            result.is_err(),
            "Should fail when validators file doesn't exist"
        );

        // Test: Generate genesis from non-existent validators file
        let result = generate_genesis_config(&validators_path, &genesis_path);
        assert!(
            result.is_err(),
            "Should fail when validators file doesn't exist"
        );
    }

    #[test]
    fn test_create_evm_consensus_file_consistency() {
        use tempfile::tempdir;

        // Test that all generated files are consistent with each other
        let temp_dir = tempdir().unwrap();
        let validators_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");
        let genesis_path = temp_dir.path().join("genesis.json");

        let authorities = 4;
        let epoch = 5;
        let stake = 2000;
        let ip_addresses = vec![
            "192.168.1.10".to_string(),
            "192.168.1.11".to_string(),
            "192.168.1.12".to_string(),
            "192.168.1.13".to_string(),
        ];
        let network_ports = vec![2024, 2025, 2026, 2027];

        // Generate all files
        generate_validators(
            &validators_path,
            authorities,
            epoch,
            stake,
            &ip_addresses,
            &network_ports,
            "consensus-node",
        )
        .unwrap();

        generate_committees(&validators_path, &committee_path, Some(epoch)).unwrap();
        generate_genesis_config(&validators_path, &genesis_path).unwrap();

        // Load and verify consistency
        let (committee, _) = load_committees(&committee_path).unwrap();
        let peer_addresses = extract_peer_addresses(&committee);

        // Verify committee has correct number of authorities
        assert_eq!(committee.size(), authorities);
        assert_eq!(committee.epoch(), epoch);
        assert_eq!(peer_addresses.len(), authorities);

        // Verify genesis config has matching number of validators
        let genesis_content = fs::read_to_string(&genesis_path).unwrap();
        let genesis_config: serde_json::Value = serde_json::from_str(&genesis_content).unwrap();
        assert_eq!(
            genesis_config["validatorAddresses"]
                .as_array()
                .unwrap()
                .len(),
            authorities
        );

        // Verify all arrays in genesis config have the same length
        let validator_addresses = genesis_config["validatorAddresses"].as_array().unwrap();
        let consensus_keys = genesis_config["consensusPublicKeys"].as_array().unwrap();
        let voting_powers = genesis_config["votingPowers"].as_array().unwrap();
        let network_addresses = genesis_config["validatorNetworkAddresses"]
            .as_array()
            .unwrap();

        assert_eq!(validator_addresses.len(), consensus_keys.len());
        assert_eq!(consensus_keys.len(), voting_powers.len());
        assert_eq!(voting_powers.len(), network_addresses.len());

        // Verify voting powers match stake
        for voting_power in voting_powers {
            assert_eq!(voting_power.as_str().unwrap(), stake.to_string());
        }
    }

    #[test]
    fn test_create_evm_consensus_with_custom_keys() {
        use consensus_config::AuthorityKeyPair;
        use fastcrypto::{bls12381, ed25519, traits::KeyPair};
        use rand::{SeedableRng, rngs::StdRng};
        use tempfile::tempdir;

        // Test creating evm-consensus with pre-generated keys
        let temp_dir = tempdir().unwrap();
        let validators_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");
        let genesis_path = temp_dir.path().join("genesis.json");

        let mut rng = StdRng::from_seed([42; 32]);

        // Generate keys manually
        let bls_keypair = bls12381::min_sig::BLS12381KeyPair::generate(&mut rng);
        let bls_private_key = bls_keypair.copy().private();
        let authority_private_key_bytes = bls_private_key.privkey.to_bytes();
        let authority_private_key_hex = hex::encode(&authority_private_key_bytes);

        let ed25519_protocol_keypair = ed25519::Ed25519KeyPair::generate(&mut rng);
        let protocol_private_key_bytes = ed25519_protocol_keypair.copy().private().0.to_bytes();
        let protocol_private_key_hex = hex::encode(protocol_private_key_bytes);

        let ed25519_network_keypair = ed25519::Ed25519KeyPair::generate(&mut rng);
        let network_private_key_bytes = ed25519_network_keypair.copy().private().0.to_bytes();
        let network_private_key_hex = hex::encode(network_private_key_bytes);

        // Create validator config with custom keys
        let validator_configs = evm_consensus::evm::ValidatorConfigs {
            validators: vec![evm_consensus::evm::ValidatorConfig {
                hostname: "custom-node-0".to_string(),
                ip_address: "10.0.0.1".to_string(),
                port: 3000,
                stake: 5000,
                authority_private_key: Some(authority_private_key_hex.clone()),
                protocol_private_key: Some(protocol_private_key_hex.clone()),
                network_private_key: Some(network_private_key_hex.clone()),
            }],
            epoch: Some(1),
        };

        let yaml_content = serde_yaml::to_string(&validator_configs).unwrap();
        fs::write(&validators_path, yaml_content).unwrap();

        // Generate committee and genesis using the custom keys
        generate_committees(&validators_path, &committee_path, None).unwrap();
        generate_genesis_config(&validators_path, &genesis_path).unwrap();

        // Verify files were created
        assert!(committee_path.exists());
        assert!(genesis_path.exists());

        // Verify genesis config uses the custom keys
        let genesis_content = fs::read_to_string(&genesis_path).unwrap();
        let genesis_config: serde_json::Value = serde_json::from_str(&genesis_content).unwrap();

        // The consensus public key should match the authority keypair we generated
        let authority_keypair = AuthorityKeyPair::new(bls_keypair);
        let public_key = authority_keypair.public();
        let expected_consensus_key_bytes = public_key.to_bytes();
        let expected_compressed: Vec<u8> = if expected_consensus_key_bytes.len() >= 48 {
            expected_consensus_key_bytes[..48].to_vec()
        } else {
            expected_consensus_key_bytes.to_vec()
        };
        let expected_consensus_key = hex::encode(&expected_compressed);

        let actual_consensus_key = genesis_config["consensusPublicKeys"][0].as_str().unwrap();
        assert_eq!(actual_consensus_key, expected_consensus_key);
    }

    #[test]
    fn test_create_evm_consensus_round_trip() {
        use tempfile::tempdir;

        // Test that we can generate configs, load them, and use them
        let temp_dir = tempdir().unwrap();
        let validators_path = temp_dir.path().join("validators.yml");
        let committee_path = temp_dir.path().join("committees.yml");

        let authorities = 3;
        let epoch = 2;
        let stake = 3000;
        let ip_addresses = vec![
            "172.16.0.1".to_string(),
            "172.16.0.2".to_string(),
            "172.16.0.3".to_string(),
        ];
        let network_ports = vec![4000, 4001, 4002];

        // Generate validators and committee
        generate_validators(
            &validators_path,
            authorities,
            epoch,
            stake,
            &ip_addresses,
            &network_ports,
            "roundtrip-node",
        )
        .unwrap();

        generate_committees(&validators_path, &committee_path, Some(epoch)).unwrap();

        // Load the committee
        let (committee, keypairs) = load_committees(&committee_path).unwrap();

        // Verify we can extract peer addresses
        let peer_addresses = extract_peer_addresses(&committee);
        assert_eq!(peer_addresses.len(), authorities);

        // Verify keypairs match authorities
        assert_eq!(keypairs.len(), authorities);

        // Verify committee properties
        assert_eq!(committee.size(), authorities);
        assert_eq!(committee.epoch(), epoch);

        // Verify each authority has correct properties
        for (i, (_, authority)) in committee.authorities().enumerate() {
            assert_eq!(u64::from(authority.stake), stake);
            assert!(authority.hostname.contains(&i.to_string()));
        }
    }
}
